---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ["base"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: base16, tags: ["base16"] }
    - { role: asdf, tags: ["asdf"] }
