---
- name: Create ~/Code/joshuap directory
  file:
    path: "/Users/{{ user.name }}/Code/joshuap"
    state: directory
  become: yes
  become_user: "{{ user.name }}"

- name: Check out mathias-dotfiles repo
  git:
    repo: "https://github.com/joshuap/mathias-dotfiles.git"
    dest: "/Users/{{ user.name }}/Code/joshuap/mathias-dotfiles"
    update: no
  become: yes
  become_user: "{{ user.name }}"

- name: Link ~/.macos
  file:
    src: "/Users/{{ user.name }}/Code/joshuap/mathias-dotfiles/.macos"
    dest: "/Users/{{ user.name }}/.macos"
    state: link
  become: yes
  become_user: "{{ user.name }}"

# Running this manually for now since the script closes the terminal.
# - name: Run ~/.macos
#   command: "~/.macos"
#   become: yes
#   become_user: "{{ user.name }}"
