---
- name: Install asdf version manager
  become_user: "{{ user.name }}"
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    version: "v0.8.1"
    dest: "/Users/{{ user.name }}/.asdf"
    update: no
  tags:
    - asdf

- name: Check installed plugins
  shell: |
    source ~/.asdf/asdf.sh
    asdf plugin-list
  register: plugin_list

- name: Install missing asdf plugins
  become_user: "{{ user.name }}"
  shell: |
    source ~/.asdf/asdf.sh
    asdf plugin-add {{ item.name }} {{ item.repo }}
  with_items: "{{ asdf_plugins }}"
  when: item.name not in plugin_list.stdout.split()
  tags:
    - asdf

- name: install asdf versions
  become_user: "{{ user.name }}"
  shell: |
    source ~/.asdf/asdf.sh
    asdf install {{ item.0.name }} {{ item.1 }}
    asdf global {{ item.0.name }} {{ item.1 }}
  with_subelements:
    - "{{ asdf_plugins }}"
    - versions
    - flags:
      skip_missing: true
  tags:
    - asdf
