---
- name: Install base16-shell
  git:
    repo: "https://github.com/chriskempson/base16-shell.git"
    dest: "/Users/{{ user.name }}/.antigen/bundles/chriskempson/base16-shell"
    update: no
  become: yes
  become_user: "{{ user.name }}"

- name: Configure base16 theme
  command: "sh /Users/{{ user.name }}/.antigen/bundles/chriskempson/base16-shell/scripts/base16-onedark.sh"
  become: yes
  become_user: "{{ user.name }}"
